<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuiLaCarne.Models\QuiLaCarne.Models.csproj" />
    <ProjectReference Include="..\QuiLaCarne.Services\QuiLaCarne.Services.csproj" />
    <ProjectReference Include="..\QuiLaCarne.Ui\QuiLaCarne.Ui.csproj" />
    <ProjectReference Include="..\ViewModels\QuiLaCarne.ViewModels.csproj" />
  </ItemGroup>

</Project>
