<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.11" />
    <PackageReference Include="Websocket.Client" Version="5.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuiLaCarne.Data\QuiLaCarne.Data.csproj" />
    <ProjectReference Include="..\QuiLaCarne.Models\QuiLaCarne.Models.csproj" />
    <ProjectReference Include="..\QuiLaCarne.Services\QuiLaCarne.Services.csproj" />
    <ProjectReference Include="..\QuiLaCarne.ViewModels\QuiLaCarne.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\qui-la-carne-logo.png" />
  </ItemGroup>

</Project>
